
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
     - db
    links:
      - db  
  db:
    image: mongo:latest
    volumes:
      - data:/var/lib/mongodb
    ports:
      - 27017:27017
volumes:
  data: {}


